version: "3.9"
services:
    mysql:
      image: mysql:8.0.28
      platform: linux/amd64
      container_name: mysql
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: development
        TZ: "Asia/Tokyo"
      volumes:
        - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      networks:
        - app_network

    app:
        container_name: "rust-app-1"
        build: ./app
        volumes:
          - ./:/usr/src
        command: sh -c "cargo watch -x run"
        ports:
          - "8080:8080"
        networks:
          - app_network
        depends_on:
          - mysql

    app2:
        container_name: "rust-app-2"
        build: ./app2
        volumes:
          - ./:/usr/src
        command: sh -c "cargo watch -x run"
        ports:
          - "8081:8081"
        networks:
          - app_network
        depends_on:
          - mysql

    frontend:
      container_name: frontend
      build: 
        context: ./frontend
        args:
          - ubuntu_version=${UBUNTU_VERSION}
          - timezone=${TIMEZONE}
          - web_server_port=${WEB_SERVER_PORT}
          - app_code_path_container=${APP_CODE_PATH_CONTAINER}
      tty: true
      env_file: .env
      volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      ports:
        - "$WEB_SERVER_PORT:$WEB_SERVER_PORT"
      networks:
        - app_network
networks:
  app_network:
    driver: bridge