FROM ubuntu:20.04

RUN apt-get update && apt-get install -y curl
RUN apt-get install build-essential -y
 
RUN mkdir -p /actix-web/www
WORKDIR /actix-web/www
 
COPY target/debug/actix-web-docker /actix-web/www/actix-web-docker

CMD ./actix-web-docker